feat(tools/check_qml_syntax): check if `linter` exists

diff --git a/tests/tools/check_qml_syntax b/tests/tools/check_qml_syntax
--- a/tests/tools/check_qml_syntax
+++ b/tests/tools/check_qml_syntax
@@ -15,6 +15,13 @@ NC='\e[0m'
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 cd $SCRIPT_DIR/..
 
+# ==============================================================================
+
+if ! [ -x "$( command -v "$LINTER" )" ]; then
+  printf "${RED}Unable to found `$LINTER`. No tests can be executed.${NC}\n"
+  exit 0
+fi
+
 printf "${BLUE}Checking qml files...${NC}\n"
 
 so_far_so_good=0
