feat(tools/check_qml_syntax): do not check qml syntax if executable cannot be found the qt lib

diff --git a/tests/tools/check_qml_syntax b/tests/tools/check_qml_syntax
--- a/tests/tools/check_qml_syntax
+++ b/tests/tools/check_qml_syntax
@@ -22,6 +22,12 @@ if ! [ -x "$( command -v "$LINTER" )" ]; then
   exit 0
 fi
 
+$("$LINTER" -v)
+if [[ $? != 0 ]] ; then
+    printf "${RED}Unable to check qml syntax.${NC}\n"
+    exit 0
+fi
+
 printf "${BLUE}Checking qml files...${NC}\n"
 
 so_far_so_good=0
